version: "3.4"

volumes:
  postgres-data:
    driver: local
    name: ctk_postgres_data
  django-static:
    driver: local
    name: ctk_django_static

services:
  postgres:
    container_name: ctk-postgres
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: ctk-server
    restart: always
    build:
      context: ./
      dockerfile: ./services/backend/Dockerfile
    image: corpulent/ctk-api:1.0.0
    working_dir: /home
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./services/backend/src:/home/server/
      - ./services/backend/configs:/home/configs/
      - django-static:/static/
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - DB_REMOTE=False
      - APP_URL=

  frontend:
    container_name: ctk-frontend
    restart: always
    build:
      context: ./
      dockerfile: ./services/frontend/Dockerfile
    image: corpulent/ctk-frontend:1.0.0
    volumes:
      - ./services/frontend/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/frontend/build:/usr/share/nginx/html/
    ports:
      - "8080:8080"
